name: studyroom
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+2


environment:
  sdk: ">=2.17.5 <3.0.0"

flutter_native_splash:
  image: "images/icon.jpg"
  color: "4DD0E1"
dependencies:
  flutter:
    sdk: flutter

  receive_sharing_intent: ^1.4.0+2
  intl: ^0.17.0
  after_layout: ^1.0.7+2
  cupertino_icons: ^1.0.2
  firebase_core: ^1.3.0
  firebase_analytics: ^8.1.2
  firebase_auth: ^2.0.0
  cloud_firestore: ^2.3.0
  firebase_storage: ^10.3.3
  photo_view: ^0.12.0
  path_provider: ^2.0.1
  image_picker: ^0.7.4
  matrix_gesture_detector: ^0.1.0
  url_launcher: ^6.1.5
  flutter_email_sender: ^5.1.0
  in_app_review: ^2.0.4
  shared_preferences: ^2.0.15
  timezone: ^0.8.0
  flutter_local_notifications: ^9.7.0
  flutter_background_service: ^2.1.3
  flutter_ringtone_player: ^3.2.0
  table_calendar: ^3.0.6
  adaptive_dialog: ^1.7.0
  custom_alert_dialog_package: ^0.0.1
  app_tracking_transparency: ^2.0.2+4
  flutter_share: ^2.0.0
  flutter_launcher_icons: ^0.9.3
  charts_flutter: ^0.12.0
  fl_chart: ^0.55.1
  syncfusion_flutter_charts: ^20.2.44
  flutter_echart: ^2.0.0
  chart_components: ^1.0.1
  simple_animations: ^5.0.0+2
adaptive_action_sheet: ^2.0.1
app_review: ^2.1.1
flutter_email_sender: ^5.1.0
admob_flutter: ^1.0.0
shared_preferences: ^2.0.15
cupertino_icons: ^0.1.2
flutter_ringtone_player: ^3.2.0
custom_alert_dialog_package: ^0.0.1
#google_mobile_ads: ^1.3.0
provider: ^6.0.1
charts: ^1.0.0+1
flutter_echart: ^1.0.0
fl_chart: ^0.45.0
flutter_background_service: ^2.1.3
table_calendar: ^3.0.0
intl: ^0.17.0
adaptive_dialog: ^1.7.0
flutter_launcher_icons: ^0.9.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"